#!/bin/bash

# Exit if any command fails
set -e

echo "Building Docker image for s3-ftp build..."
docker build -t turbovote/s3-ftp-build - < Dockerfile.build
echo "Done."

echo "Building s3-ftp..."

docker run --rm=true -v `pwd`:/s3-ftp \
           turbovote/s3-ftp-build

echo "Done."
